- LICENSE
> Docs: create LICENSE

- core-design-system/src/main/java/com/comit/core_design_system/button/button.kt
- core-design-system/src/main/java/com/comit/core_design_system/color/SimTongColor.kt
- core-design-system/src/main/java/com/comit/core_design_system/component/TextField.kt
- core-design-system/src/main/java/com/comit/core_design_system/dialog/bottomSheet.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/findemployeenum/FindEmployeeNumScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/CheckCertificationNumberScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FixPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signin/SignInScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signup/SignUpNameScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signup/SignUpNicknameScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signup/SignUpPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signup/SignUpVerifyScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixBaseScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixEmailScreen.kt
* 버튼의 구조를 변경하였습니다. (인자를 통해 색깔 타입을 받아올 수 있도록 하였습니다)
> Merge: SIMT-25 design system button argument color

- core-design-system/src/main/java/com/comit/core_design_system/util/Anim.kt
- feature/feature-mypage/build.gradle.kts
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixBaseScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixEmailScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixPassword.kt
- navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
- 이메일 수정 버튼 색 변경 및 화면 전환 애니메이션 추가
- 마이페이지 수정으로 넘어가는 버튼 범위 변경
> Merge: SIMT-35 이메일 수정 및 마이페이지 수정

- data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
- data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
- domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
- domain/src/main/java/com/comit/domain/usecase/ChangeEmailUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/ChangeNicknameUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/ChangeProfileImageUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/ChangeSpotUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/CheckNicknameDuplicationUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/FetchUserInformationUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/SignUpUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/VerificationEmployeeUseCase.kt
- model/src/main/java/com/comit/model/User.kt
- remote/src/main/java/com/comit/remote/api/AuthAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
- remote/src/main/java/com/comit/remote/request/users/ChangeProfileImageRequest.kt
- remote/src/main/java/com/comit/remote/request/users/ChangeSpotRequest.kt
- remote/src/main/java/com/comit/remote/response/users/FetchUserInformationResponse.kt
> Merge: SIMT-41 AuthAPI

- data/src/main/java/com/comit/data/datasource/RemoteEmailDataSource.kt
- data/src/main/java/com/comit/data/repository/EmailRepositoryImpl.kt
- di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
- di/src/main/java/com/comit/di/RepositoryModule.kt
- domain/src/main/java/com/comit/domain/repository/EmailRepository.kt
- domain/src/main/java/com/comit/domain/usecase/email/CheckEmailCodeUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/email/SendEmailCodeUseCase.kt
- remote/src/main/java/com/comit/remote/api/EmailAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteEmailDataSourceImpl.kt
> Merge: SIMT-44 Email API

- data/src/main/java/com/comit/data/datasource/RemoteHolidayDataSource.kt
- data/src/main/java/com/comit/data/repository/HolidayRepositoryImpl.kt
- di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
- di/src/main/java/com/comit/di/RepositoryModule.kt
- domain/src/main/java/com/comit/domain/repository/HolidayRepository.kt
- domain/src/main/java/com/comit/domain/usecase/holiday/DayOffHolidaysUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/holiday/FetchHolidaysUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/holiday/SetAnnualUseCase.kt
- domain/src/main/java/com/comit/domain/usecase/holiday/SetWorkUseCase.kt
- model/src/main/java/com/comit/model/HolidayList.kt
- remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
- remote/src/main/java/com/comit/remote/api/MenuAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteMenuDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
- remote/src/main/java/com/comit/remote/response/holidays/FetchHolidaysResponse.kt
- remote/src/main/java/com/comit/remote/response/holidays/SimpleHolidaysResponse.kt
> Merge: SIMT-47 Holidays API

- buildSrc/src/main/java/ProjectProperties.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
- data/src/main/java/com/comit/data/datasource/RemoteCommonsDataSource.kt
- data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/java/com/comit/data/repository/CommonsRepositoryImpl.kt
- di/src/main/java/com/comit/di/LocalDataSourceModule.kt
- di/src/main/java/com/comit/di/PreferenceModule.kt
- di/src/main/java/com/comit/di/ProvideContext.kt
- domain/src/main/java/com/comit/domain/repository/CommonsRepository.kt
- local/build.gradle.kts
- local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
- local/src/main/java/com/comit/local/extension/datastore.kt
- local/src/main/java/com/comit/local/extension/time.kt
- local/src/main/java/com/comit/local/preference/AuthPreference.kt
- local/src/main/java/com/comit/local/preference/AuthPreferenceImpl.kt
- local/src/main/java/com/comit/local/preference/ProvideDataStore.kt
- remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteCommonsDataSourceImpl.kt
* Auth Local부분 작업
* Local 베이스 코드 작업
* Authoirzation Interceptor 작업
* Gradle 변경 (SDK 버전, Preference DataStore추가)
> Merge: SIMT-48 Authoirzation Interceptor

- common-compose/src/main/java/com/comit/common/layout.kt
- common-compose/src/main/java/com/comit/common/timer.kt
- core-design-system/src/main/java/com/comit/core_design_system/util/time.kt
- data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/java/com/comit/data/util/SimTongApiCall.kt
- domain/src/main/java/com/comit/domain/exception/HttpException.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/FindPasswordContract.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/AuthFindScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordEmailCodeScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNameScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNicknameScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpPasswordScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpVerifyScreen.kt
- feature/feature-auth/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
- feature/feature-auth/src/main/res/values/string.xml
- remote/src/main/java/com/comit/remote/api/EmailAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteEmailDataSourceImpl.kt
* 비밀번호 찾기 구조 변경
* 비밀번호 찾기 MVI로 마이그레이션
* 비밀번호 찾기 비즈니스 로직과 연결
> Merge: SIMT-61 비밀번호 찾기 Refactor & Connect

- buildSrc/src/main/java/Versions.kt
- data/build.gradle.kts
- data/src/main/java/com/comit/data/extension/MultiPart.kt
- data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
- data/src/main/java/com/comit/data/interceptor/ReissueTokenResponse.kt
> Merge: SIMT-60 fix token interceptor

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- feature/feature-home/build.gradle.kts
- feature/feature-home/src/main/AndroidManifest.xml
- feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/HolidayWebViewScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/SalaryWebViewScreen.kt
- navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
> Merge: SIMT-71 Salary WebView connect

- common-compose/src/main/java/com/comit/common/SimImageUploadLayout.kt
- data/src/main/java/com/comit/data/datasource/RemoteScheduleDataSource.kt
- data/src/main/java/com/comit/data/repository/ScheduleRepositoryImpl.kt
- data/src/main/java/com/comit/data/util/SimTongApiCall.kt
- domain/src/main/java/com/comit/domain/repository/ScheduleRepository.kt
- domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
- feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleViewModel.kt
- feature/feature-home/src/main/res/values/string.xml
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
- remote/src/main/java/com/comit/remote/api/ScheduleAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteScheduleDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/request/schedules/ChangePersonalScheduleRequest.kt
> Merge: SIMT-74 일정 수정

- feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceScreen.kt
- 홈화면 스크롤 수정
- 일정확인 아이템 버튼 ui 수정
> Merge: SIMT-78 일정 확인 페이지 ui수정

- app/release/output-metadata.json
- app/src/main/java/com/comit/simtong/handler/SimTongExceptionHandler.kt
- feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/navigation/AuthNavigation.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/error/ErrorScreen.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/utils/AuthDeepLinkKeyUtil.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
- feature/feature-onboarding/src/main/res/values/string.xml
- navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
resolves : SIMT-80
UnknownException 발생 시 대응
* ErrorScreen으로 이동, 에러 정보 표시
* 이전 페이지로 이동 후 재시도 가능
* MyPage쪽은 충돌을 우려하여 아직 연동 X
* 인터넷 관련 처리를 따로 작업해야 함
> Merge: SIMT-80 GlobalException Handling

- app/src/main/java/com/comit/simtong/root/MainActivity.kt
- feature/feature-home/src/main/java/com/comit/feature_home/mvi/CloseDayContract.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/CloseDayViewModel.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
- 휴무일 설정이 안되던 버그 수정
- 여러 예외처리 추가
> Merge: SIMT-85 일정 수정 페이지 버그수정

- core-design-system/src/main/java/com/comit/core_design_system/component/CarrotMarket.kt
- core-design-system/src/main/java/com/comit/core_design_system/component/Comment.kt
- core-design-system/src/main/java/com/comit/core_design_system/component/IdeaComponent.kt
- core-design-system/src/main/java/com/comit/core_design_system/component/NoticeBoardItem.kt
- core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
- core-design-system/src/main/java/com/comit/core_design_system/modifier/cutter.kt
- core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
- data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
- di/src/main/java/com/comit/di/NetworkModule.kt
- feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
* 더블 클릭 방지
MutableClickEventsCutter를 사용해 해결
simClickabled 사용 시 적용
* 더블 클릭을 허용하고 싶은 경우 singleClicked argument 사용 가능
> Merge: SIMT-89 disbled doubleClicked

- app/build.gradle.kts
- app/proguard-rules.pro
- build.gradle.kts
- buildSrc/src/main/java/BuildPlugins.kt
- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/ProjectProperties.kt
- buildSrc/src/main/java/Versions.kt
- domain/build.gradle.kts
- domain/src/main/java/com/comit/domain/exception/ThrowUnknownException.kt
* Firebase Crashlytics & Analytics 추가
* Version Name 0.0.3-alpha로 변경
> Merge: SIMT-82, SIMT-81 Firebase Crashlytics & Analytics

- core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
- core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
Content로 Text가 있을 경우 clickable이 동작하지 않는 문제 해결
> Merge: SIMT-98 fix clickable

- feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
> refactor: SIMT-104 메인 페이지, 일정 작성 달력 크기 수정

- feature/feature-home/src/main/java/com/comit/feature_home/screen/SalaryWebViewScreen.kt
https://limsaehyun.atlassian.net/browse/SIMT-106?atlOrigin=eyJpIjoiOWIyNmJmZTI5Y2YxNDNlNDlkNTc2OGM2NjgyNDU4NzgiLCJwIjoiaiJ9
> Merge: SIMT-106 enabled Webview JS

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/comit/simtong/firebase/FCMManager.kt
- app/src/main/java/com/comit/simtong/firebase/firebase.kt
- app/src/main/java/com/comit/simtong/root/MainActivity.kt
- app/src/main/java/com/comit/simtong/root/MainViewModel.kt
- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
- data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
- data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
- domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
- domain/src/main/java/com/comit/domain/usecase/users/SaveDeviceTokenUseCase.kt
- feature/feature-onboarding/src/main/AndroidManifest.xml
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
- feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
- local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
- local/src/main/java/com/comit/local/preference/AuthPreference.kt
- local/src/main/java/com/comit/local/preference/AuthPreferenceImpl.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/request/users/SignInRequest.kt
- remote/src/main/java/com/comit/remote/request/users/SignUpRequest.kt
* 디바이스 토큰 추가에 대해 대응
* FCM Manager 작업
* 디바이스 토큰을 가져와서 저장
> Merge: SIMT-111 FetchAndSave DeviceToken

- feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
https://limsaehyun.atlassian.net/browse/SIMT-115?atlOrigin=eyJpIjoiNzZiNzFkMTljYzVlNDhiNTliN2Q1MGNhYjIyY2ZkYjUiLCJwIjoiaiJ9
[SIMT-115]: https://limsaehyun.atlassian.net/browse/SIMT-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Merge: SIMT-115 나위 급여 정보, 휴무표 작성 버튼 리플 효과 범위 수정

- app/src/main/java/com/comit/simtong/root/MainViewModel.kt
- feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
- feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
- remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
- remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
- remote/src/main/java/com/comit/remote/request/holidays/SetAnnualRequest.kt
- remote/src/main/java/com/comit/remote/request/holidays/SetWorkRequest.kt
- 연차, 근무 일정 설정 api 변경에 따른 request 메서드를 변경하였습니다
- 연차, 근무 일정 설정시 날짜가 잘 들어가지 않아 400이 뜨는 오류를 고쳤습니다
- https://limsaehyun.atlassian.net/browse/SIMT-110?atlOrigin=eyJpIjoiZWQ0YzI2ODAyN2M2NDA5YmExMWY3ZmM0OTk1NjcyY2UiLCJwIjoiaiJ9
[SIMT-110]: https://limsaehyun.atlassian.net/browse/SIMT-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 연차, 근무 신청 405에러 수정
